### PR TITLE
oc package now is able to reuse modules in component path

### LINKED ISSUE #943: oc package <componentPath> does not find modules in componentPath
## *Who* is the bug affecting?
component creators

## *What* is affected by this bug?
oc cli tool

## *When* does this occur?
When packaging component

## *Where* on the platform does it happen?
cli

## *How* do we replicate the issue?
- npm install -g oc@0.44.13
- Create an OC component (e.g. temp-oc)
- npm install in temp-oc root
- npm build temp-oc
- cd ..
- oc package ./temp-oc
- see the error
```
Packaging -> /Users/x/components/temp-oc/_package
Ensuring dependencies are loaded...
Trying to install missing modules: foo@^1.3.21, bar@^0.1.0
If you aren't connected to the internet, or npm isn't configured then this step will fail...FAIL
```

Note: `foo` and `bar` are installed through internal npm artifact

### working example
- npm install -g oc@0.44.13
- Create an OC component (e.g. temp-oc)
- npm install in temp-oc root
- npm build temp-oc
- oc package .
- output:
```
Packaging -> /Users/x/components/temp-oc/_package
Ensuring dependencies are loaded...
Packaged -> /Users/x/components/temp-oc/_package
```

## Expected behavior (i.e. solution)
oc package <componentPath> should respect node_modules instaled in `componentPath/node_modules`

## What version of OC, Node.js and OS are you using?
oc@0.44.13, Node v8.11.1, Mac

## Other Comments
possibly problem comes from this line
https://github.com/opencomponents/oc/blob/efeadfbfda5413080e7e908f112e20c71bb9f311/src/cli/facade/package.js#L21

### PR DESCRIPTION
**Pull request by NimaSoroush**
**Closing issues**
closes #943

**What existing problem does the pull request solve?**

A new parameter 'useComponentDependencies' being introduced to package command that make oc package command able to reuse already installed modules in component directory instead of reinstall them. Reinstalling missing modules makes more network call and makes the release process longer also if missing modules are stored in internal npm artifact with required credential to retrieve them then package command will fail without clear understanding of the issue

**New function linkMissingDependencies**

Similar to `installMissingDependencies`, `linkMissingDependencies` will try to create a symbolic link by **fs symlink** to reference the missing dependency to OC's dependency in node_modules folder

**Test plan (required)**

As described in #943, now this scenario works without throwing error

- Create an OC component (e.g. temp-oc)
- npm install in temp-oc root
- npm build temp-oc
- cd ..
- oc package ./temp-oc
- and output is 
```
Packaging -> /Users/x/components/temp-oc/_package
Ensuring dependencies are loaded...
Packaged -> /Users/x/components/temp-oc/_package
```

### CODE REVIEW

File: tasks/npm-publish.js [hunk 1]
```diff
@@ -27,7 +25,7 @@ cmd.on('error', () => {
 
 cmd.on('close', code => {
   if (code === 0) {
-    log.complete('npm publish succeded');
+    log.complete('npm publish succeeded');
```
Comment (matteofigus) [inline tasks/npm-publish.js]: 👍

**Comment by NimaSoroush** [comment]
@matteofigus : Yeah that makes sense. Applied your suggestion!

**Comment by NimaSoroush** [comment]
Great! Thanks @matteofigus for review and accepting the PR.

May I ask when this goes live?

**Comment by matteofigus** [comment]
Published now @NimaSoroush

**Comment by matteofigus** [comment]
A little favour @NimaSoroush, when you have some time, are you able to update https://github.com/opencomponents/oc/wiki/Cli as well? Thanks!

**Comment by NimaSoroush** [comment]
@matteofigus , Sure, I will definitely do

**Comment by NimaSoroush** [comment]
@matteofigus : Done!
